import dataclasses
import importlib.metadata
import json
import logging
import os
import time
import uuid
from collections.abc import AsyncGenerator
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Generator

import pytest
import pytest_asyncio
import requests
from dotenv import load_dotenv
from fastmcp import Client, Context, FastMCP
from kbcstorage.client import Client as SyncStorageClient
from mcp.server.session import ServerSession
from mcp.shared.context import RequestContext
from mcp.types import ClientCapabilities, Implementation, InitializeRequestParams

from integtests.project_lock import (
    DEFAULT_MAX_WAIT_MINUTES,
    DEFAULT_POLL_INTERVAL_SECONDS,
    DEFAULT_TTL_MINUTES,
    AcquiredProject,
    ProjectPool,
    verify_project_endpoint,
)
from keboola_mcp_server.clients.client import KeboolaClient
from keboola_mcp_server.config import Config, ServerRuntimeInfo
from keboola_mcp_server.mcp import ServerState, SessionStateMiddleware
from keboola_mcp_server.server import create_server
from keboola_mcp_server.workspace import WorkspaceManager

LOG = logging.getLogger(__name__)

_project_pool: ProjectPool | None = None
_acquired_project: AcquiredProject | None = None
_project_info: str | None = None
_project_info_printed: bool = False

POOL_STORAGE_API_URL_ENV_VAR = 'INTEGTEST_POOL_STORAGE_API_URL'
STORAGE_API_TOKENS_ENV_VAR = 'INTEGTEST_STORAGE_TOKENS'  # space-separated pool of tokens
# The second pair of token/schema for testing simultaneous access to two different projects.
STORAGE_API_TOKEN_ENV_VAR_2 = 'INTEGTEST_STORAGE_TOKEN_PRJ2'
WORKSPACE_SCHEMA_ENV_VAR_2 = 'INTEGTEST_WORKSPACE_SCHEMA_PRJ2'
# We reset dev environment variables to integtest values to ensure tests run locally using .env settings.
DEV_STORAGE_API_URL_ENV_VAR = 'STORAGE_API_URL'
DEV_STORAGE_TOKEN_ENV_VAR = 'KBC_STORAGE_TOKEN'
DEV_WORKSPACE_SCHEMA_ENV_VAR = 'KBC_WORKSPACE_SCHEMA'
INTEGTEST_CLIENT_INFO = Implementation(
    name='kbc-mcp-integtests', version=importlib.metadata.version('keboola_mcp_server')
)
INTEGTEST_USER_AGENT = f'{INTEGTEST_CLIENT_INFO.name}/{INTEGTEST_CLIENT_INFO.version}'


@dataclass(frozen=True)
class BucketDef:
    bucket_id: str
    display_name: str


@dataclass(frozen=True)
class TableDef:
    bucket_id: str
    table_name: str
    table_id: str

    @property
    def file_path(self) -> Path:
        """
        Path to the CSV file containing the table data.
        """
        return _data_dir() / 'proj' / 'buckets' / self.bucket_id / f'{self.table_name}.csv'


@dataclass(frozen=True)
class ConfigDef:
    component_id: str
    configuration_id: str | None  # Will be generated by Storage API
    internal_id: str

    @property
    def file_path(self) -> Path:
        """
        Path to the JSON file containing the configuration.
        """
        return _data_dir() / 'proj' / 'configs' / self.component_id / f'{self.internal_id}.json'


@dataclass(frozen=True)
class ProjectDef:
    project_id: str
    buckets: list[BucketDef]
    tables: list[TableDef]
    configs: list[ConfigDef]


@pytest.fixture(scope='session')
def env_file_loaded() -> bool:
    return load_dotenv()


@pytest.fixture(autouse=True)
def _patch_fastmcp_client_default_info(mocker) -> None:
    # Ensure all fastmcp.Client instances in integration tests use a distinct identity
    # unless a test intentionally provides a different client_info.
    original_init = Client.__init__

    def _init_with_integtest_client_info(self, *args: Any, **kwargs: Any) -> None:
        kwargs.setdefault('client_info', INTEGTEST_CLIENT_INFO)
        original_init(self, *args, **kwargs)

    mocker.patch.object(Client, '__init__', _init_with_integtest_client_info)


@pytest.fixture(scope='session', autouse=True)
def _patch_session_middleware_user_agent() -> Generator[None, None, None]:
    # Force a distinct User-Agent for outbound Keboola API requests during integration tests.
    monkeypatch = pytest.MonkeyPatch()
    original_get_headers = SessionStateMiddleware._get_headers.__func__

    def _get_headers_with_integtest_ua(
        cls: type[SessionStateMiddleware], runtime_info: ServerRuntimeInfo
    ) -> dict[str, Any]:
        headers = original_get_headers(cls, runtime_info)
        headers['User-Agent'] = INTEGTEST_USER_AGENT
        return headers

    monkeypatch.setattr(SessionStateMiddleware, '_get_headers', classmethod(_get_headers_with_integtest_ua))
    try:
        yield
    finally:
        monkeypatch.undo()


@pytest.fixture(scope='session')
def env_init(env_file_loaded: bool, storage_api_token: str, storage_api_url: str, workspace_schema: str) -> bool:
    # We reset the development environment variables to the values of the integtest environment variables.
    os.environ[DEV_STORAGE_API_URL_ENV_VAR] = storage_api_url
    os.environ[DEV_STORAGE_TOKEN_ENV_VAR] = storage_api_token
    os.environ[DEV_WORKSPACE_SCHEMA_ENV_VAR] = workspace_schema
    return env_file_loaded


def _data_dir() -> Path:
    return Path(__file__).parent / 'data'


@pytest.fixture(scope='session')
def storage_api_url(env_file_loaded: bool) -> str:
    storage_api_url = os.getenv(POOL_STORAGE_API_URL_ENV_VAR)
    assert storage_api_url, f'{POOL_STORAGE_API_URL_ENV_VAR} must be set'
    return storage_api_url


@pytest.fixture(scope='session')
def storage_api_token(project_lock: AcquiredProject) -> str:
    return project_lock.endpoint.storage_api_token


@pytest.fixture(scope='session')
def mcp_config(storage_api_token: str, storage_api_url: str) -> Config:
    return Config(storage_api_url=storage_api_url, storage_token=storage_api_token)


@pytest.fixture(scope='session')
def workspace_schema(_clean_project: str, storage_api_token: str, storage_api_url: str) -> Generator[str, Any, None]:
    """
    Create one read-only workspace for the whole test session and yield its schema.

    The workspace is created once (session scope), reused across all tests, and deleted
    on teardown.
    """
    # sync_storage_client is function-scoped; build a session-scoped client here.
    storage_client = _sync_storage_client(storage_api_token, storage_api_url)
    token_info = storage_client.tokens.verify()
    backend = token_info['owner'].get('defaultBackend')
    # Mirror the MCP server's own per-backend workspace login type (see WorkspaceManager._create_ws).
    if backend == 'snowflake':
        login_type = 'snowflake-person-sso'
    elif backend == 'bigquery':
        login_type = 'default'
    else:
        raise RuntimeError(f'Unexpected project default backend: {backend!r} (expected snowflake or bigquery)')

    LOG.info(f'Creating a read-only {backend} workspace for the test session')
    workspace = storage_client.workspaces.create(
        backend=backend,
        login_type=login_type,
        # kbcstorage maps read_all_objects to the readOnlyStorageAccess flag (read-only storage access).
        read_all_objects=True,
    )
    workspace_id = workspace['id']
    schema = workspace['connection']['schema']
    LOG.info(f'Created read-only workspace {workspace_id} (schema {schema})')
    try:
        yield schema
    finally:
        LOG.info(f'Deleting test-session workspace {workspace_id}')
        try:
            storage_client.workspaces.delete(workspace_id)
        except Exception:
            LOG.exception(f'Failed to delete test-session workspace {workspace_id}')


@pytest.fixture(scope='session')
def storage_api_token_2(env_file_loaded: bool) -> str | None:
    return os.getenv(STORAGE_API_TOKEN_ENV_VAR_2)


@pytest.fixture(scope='session')
def workspace_schema_2(env_file_loaded: bool) -> str | None:
    return os.getenv(WORKSPACE_SCHEMA_ENV_VAR_2)


@pytest.fixture(scope='session')
def shared_datadir_ro() -> Path:
    """
    Session-scoped access to shared data directory for integration tests.
    Do not modify the data in this directory.
    For function-scoped access to the data, use `shared_datadir` fixture provided by `pytest-datadir`,
    which creates a temporary copy of the data which can therefore be modified.
    """
    return _data_dir()


_BUCKET_DEFS_IN = [
    BucketDef(bucket_id='in.c-test_bucket_01', display_name='test_bucket_01'),
    BucketDef(bucket_id='in.c-test_bucket_02', display_name='test_bucket_02'),
]


def _create_buckets(storage_client: SyncStorageClient) -> list[BucketDef]:
    for bucket in _BUCKET_DEFS_IN:
        LOG.info(f'Creating bucket with display name={bucket.display_name}')
        created_bucket = storage_client.buckets.create(bucket.display_name)
        assert created_bucket['id'] == bucket.bucket_id
        assert created_bucket['displayName'] == bucket.display_name

    return _BUCKET_DEFS_IN


_TABLE_DEFS_IN = [
    TableDef(
        bucket_id='in.c-test_bucket_01',
        table_name='test_table_01',
        table_id='in.c-test_bucket_01.test_table_01',
    ),
]


def _create_tables(storage_client: SyncStorageClient) -> list[TableDef]:
    for table in _TABLE_DEFS_IN:
        LOG.info(f'Creating table with name={table.table_name}')
        created_table_id = storage_client.tables.create(
            bucket_id=table.bucket_id,
            name=table.table_name,
            file_path=str(table.file_path),
        )
        assert created_table_id == table.table_id

    return _TABLE_DEFS_IN


_CONFIG_DEFS_IN = [
    ConfigDef(
        component_id='ex-generic-v2',
        configuration_id=None,
        internal_id='test_config1',
    ),
    ConfigDef(
        component_id='keboola.snowflake-transformation',
        configuration_id=None,
        internal_id='test_config2',
    ),
]


def _create_configs(storage_client: SyncStorageClient) -> list[ConfigDef]:
    configs = []
    for config in _CONFIG_DEFS_IN:
        LOG.info(f'Creating config with internal ID={config.internal_id}')
        with config.file_path.open('r', encoding='utf-8') as cfg_file:
            created_config = storage_client.configurations.create(
                component_id=config.component_id,
                name=config.internal_id,
                configuration_id=None,
                configuration=json.load(cfg_file),
            )
        config = dataclasses.replace(config, configuration_id=created_config['id'])
        configs.append(config)
        LOG.info(f'Created config with component ID={config.component_id} and config ID={config.configuration_id}')

    return configs


def _sync_storage_client(storage_api_token: str, storage_api_url: str) -> SyncStorageClient:
    client = SyncStorageClient(storage_api_url, storage_api_token)
    token_info = client.tokens.verify()
    LOG.info(
        f'Authorized as "{token_info["description"]}" ({token_info["id"]}) '
        f'to project "{token_info["owner"]["name"]}" ({token_info["owner"]["id"]}) '
        f'at "{client.root_url}" stack.'
    )
    return client


# Buckets the integration fixtures/tests create are all stage-prefixed "c-test*". A real
# (non-dedicated) project's buckets won't match, so this doubles as a safety guard against a
# misconfigured INTEGTEST_STORAGE_TOKENS pointing at a project whose data must not be wiped.
_TEST_BUCKET_ID_PREFIXES = ('in.c-test', 'out.c-test', 'sys.c-test')

# Workspaces not created by the tests that must never be deleted (matched on the creator token).
_STATIC_WORKSPACE_CREATORS = frozenset({'Background Indexing Token'})


def _guard_dedicated_test_project(storage_client: SyncStorageClient, project_id: str) -> None:
    """Refuse to reset the project unless it looks like a dedicated integtest project.

    The integ fixtures/tests only ever create stage-prefixed ``*.c-test*`` buckets, so a project
    holding any other bucket is almost certainly not a dedicated test project. Failing here (instead
    of deleting) protects against a misconfigured ``INTEGTEST_STORAGE_TOKENS`` that points at a
    project whose data must not be wiped.
    """
    foreign = [b['id'] for b in storage_client.buckets.list() if not b['id'].startswith(_TEST_BUCKET_ID_PREFIXES)]
    if foreign:
        pytest.fail(
            f'Refusing to reset project {project_id}: found non-test buckets {foreign}. '
            f'INTEGTEST_STORAGE_TOKENS may be pointing at a non-dedicated project.'
        )


def _purge_project(storage_client: SyncStorageClient, storage_api_url: str, project_id: str) -> None:
    """Reset a dedicated integtest project to a clean state.

    Integration tests run against a shared pool of projects acquired per run. A prior session that
    was cancelled (a new push/rebase cancels the in-flight CI run) or timed out before its teardown
    leaves buckets, configurations, workspaces and branch metadata behind. The next run that locks
    the project would then fail an empty-project assertion *before* its own teardown runs, so the
    project stays dirty and wedges every subsequent run. Purging here lets the shared pool self-heal.
    """
    _guard_dedicated_test_project(storage_client, project_id)

    buckets = storage_client.buckets.list()
    workspaces = [
        w
        for w in storage_client.workspaces.list()
        if w.get('creatorToken', {}).get('description') not in _STATIC_WORKSPACE_CREATORS
    ]
    components = storage_client.components.list(include=['configuration'])
    branch_meta = [
        m for m in storage_client.branches.metadata('default') if m.get('key') == WorkspaceManager.MCP_META_KEY
    ]

    if buckets or workspaces or any(c.get('configurations') for c in components) or branch_meta:
        LOG.warning(
            f'Project {project_id} was not clean: {len(buckets)} bucket(s), {len(workspaces)} workspace(s), '
            f'{sum(len(c.get("configurations", [])) for c in components)} config(s), '
            f'{len(branch_meta)} workspace-metadata entr(ies) — likely an interrupted prior run. Purging.'
        )

    for bucket in buckets:
        storage_client.buckets.delete(bucket['id'], force=True)

    for workspace in workspaces:
        storage_client.workspaces.delete(workspace['id'])

    for component in components:
        component_id = component['id']
        for config in component.get('configurations', []):
            # Double delete because the first delete only moves the configuration to the trash.
            storage_client.configurations.delete(component_id, config['id'])
            storage_client.configurations.delete(component_id, config['id'])

    # kbcstorage exposes no branch-metadata delete; the MCP WorkspaceManager stamps MCP_META_KEY on
    # the default branch when it creates a workspace, so remove leftovers with a raw request.
    for meta in branch_meta:
        resp = requests.delete(
            f'{storage_api_url.rstrip("/")}/v2/storage/branch/default/metadata/{meta["id"]}',
            headers={'X-StorageApi-Token': storage_client.token},
        )
        resp.raise_for_status()


@pytest.fixture(scope='session')
def _clean_project(storage_api_token: str, storage_api_url: str) -> str:
    """Reset the acquired pool project before any other fixture creates resources, so an interrupted
    prior run can't wedge the shared pool. Other session fixtures depend on this to order it first."""
    storage_client = _sync_storage_client(storage_api_token, storage_api_url)
    project_id: str = storage_client.tokens.verify()['owner']['id']
    _purge_project(storage_client, storage_api_url, project_id)
    return project_id


@pytest.fixture(scope='session')
def keboola_project(
    _clean_project: str, env_init: bool, storage_api_token: str, storage_api_url: str
) -> Generator[ProjectDef, Any, None]:
    """
    Sets up a Keboola project with items needed for integration tests,
    such as buckets, tables and configurations.
    The project is reset to a clean state first (see _clean_project) and cleaned up after the tests.
    """
    # Cannot use keboola_client fixture because it is function-scoped
    storage_client = _sync_storage_client(storage_api_token, storage_api_url)
    token_info = storage_client.tokens.verify()
    project_id: str = token_info['owner']['id']

    buckets = _create_buckets(storage_client)
    tables = _create_tables(storage_client)
    configs = _create_configs(storage_client)

    if 'global-search' in token_info['owner'].get('features', []):
        # Give the global search time to catch up on the changes done in the testing project.
        # See https://help.keboola.com/management/global-search/#limitations for more info.
        time.sleep(10)

    LOG.info(f'Test setup for project {project_id} complete')
    yield ProjectDef(project_id=project_id, buckets=buckets, tables=tables, configs=configs)

    LOG.info(f'Cleaning up Keboola project with ID={project_id}')
    current_buckets = storage_client.buckets.list()
    for bucket in current_buckets:
        bucket_id = bucket['id']
        LOG.info(f'Deleting bucket with ID={bucket_id}')
        storage_client.buckets.delete(bucket_id, force=True)

    for config in configs:
        LOG.info(f'Deleting config with component ID={config.component_id} and config ID={config.configuration_id}')
        storage_client.configurations.delete(config.component_id, config.configuration_id)
        # Double delete because the first delete moves the configuration to the trash
        storage_client.configurations.delete(config.component_id, config.configuration_id)


def _setup_pool(storage_api_url: str) -> tuple[ProjectPool, AcquiredProject]:
    tokens_raw = os.getenv(STORAGE_API_TOKENS_ENV_VAR, '').strip()
    if not tokens_raw:
        raise RuntimeError(
            f'{STORAGE_API_TOKENS_ENV_VAR} must be set to a non-empty space-separated list of project tokens'
        )
    tokens = tokens_raw.split()

    endpoints = [verify_project_endpoint(storage_api_url, t) for t in tokens]

    pool = ProjectPool(
        endpoints=endpoints,
        ttl_minutes=int(os.getenv('INTEGTEST_LOCK_TTL_MINUTES', str(DEFAULT_TTL_MINUTES))),
        poll_interval_seconds=int(
            os.getenv('INTEGTEST_LOCK_POLL_INTERVAL_SECONDS', str(DEFAULT_POLL_INTERVAL_SECONDS))
        ),
        max_wait_minutes=int(os.getenv('INTEGTEST_LOCK_MAX_WAIT_MINUTES', str(DEFAULT_MAX_WAIT_MINUTES))),
    )
    return pool, pool.acquire()


def pytest_collection_finish(session: pytest.Session) -> None:
    """Pytest hook called after collection is finished, before any tests run.

    Eagerly acquires the project lock and prints project/token info to the terminal
    so it appears before test progress output — avoiding the ANSI overwrite issue that
    occurs when writing during fixture setup (which runs mid-progress-line in compact mode).

    If acquisition fails (e.g. missing env vars), the hook logs a warning and returns
    without raising; the ``project_lock`` fixture will then acquire lazily and call
    ``pytest.fail()`` with a proper error message.

    See also:
        https://docs.pytest.org/en/stable/reference/reference.html#pytest.hookspec.pytest_collection_finish
    """
    global _project_pool, _acquired_project, _project_info, _project_info_printed
    needs_lock = any('project_lock' in getattr(item, 'fixturenames', []) for item in session.items)
    if not needs_lock:
        return
    load_dotenv()
    storage_api_url = os.getenv(POOL_STORAGE_API_URL_ENV_VAR)
    if not storage_api_url:
        return
    try:
        _project_pool, _acquired_project = _setup_pool(storage_api_url)
    except Exception as exc:
        LOG.warning(f'[integtest] Eager project lock acquisition failed: {exc}')
        return
    ep = _acquired_project.endpoint
    _project_info = ep.describe()
    reporter = session.config.pluginmanager.get_plugin('terminalreporter')
    if reporter is not None:
        reporter.write_sep('-', 'integtest project')
        reporter.write_line(_project_info)
        _project_info_printed = True


def pytest_terminal_summary(terminalreporter: Any, exitstatus: int, config: pytest.Config) -> None:
    if _project_info is not None and not _project_info_printed:
        terminalreporter.write_sep('-', 'integtest project')
        terminalreporter.write_line(_project_info)


@pytest.fixture(scope='session')
def project_lock(env_file_loaded: bool, storage_api_url: str) -> Generator[AcquiredProject, Any, None]:
    """
    Acquires a distributed lock on a Keboola test project via branch metadata.

    Requires INTEGTEST_STORAGE_TOKENS to be set to a space-separated list of project
    tokens, one per project in the pool. The Storage API URL is provided by the
    storage_api_url fixture (INTEGTEST_POOL_STORAGE_API_URL).

    Yields AcquiredProject(endpoint, lock_info) so callers know which project was
    selected. The storage_api_token fixture reads its value from the acquired endpoint.

    The project lock is normally acquired eagerly in pytest_collection_finish before
    tests start. This fixture falls back to acquiring it lazily if that hook did not run.
    """
    global _project_pool, _acquired_project, _project_info
    if _acquired_project is None:
        try:
            _project_pool, _acquired_project = _setup_pool(storage_api_url)
        except RuntimeError as exc:
            pytest.fail(str(exc))
        ep = _acquired_project.endpoint
        _project_info = ep.describe()
    try:
        yield _acquired_project
    finally:
        if _project_pool is not None and _acquired_project is not None:
            _project_pool.release(_acquired_project)
        _acquired_project = None
        _project_pool = None


@pytest.fixture(scope='session')
def buckets(keboola_project: ProjectDef) -> list[BucketDef]:
    return keboola_project.buckets


@pytest.fixture(scope='session')
def tables(keboola_project: ProjectDef) -> list[TableDef]:
    return keboola_project.tables


@pytest.fixture(scope='session')
def configs(keboola_project: ProjectDef) -> list[ConfigDef]:
    return keboola_project.configs


@pytest.fixture
def sync_storage_client(storage_api_token: str, storage_api_url: str) -> SyncStorageClient:
    """Gets the ordinary (synchronous) client from the official Keboola SDK (i.e. `kbcstorage` package)."""
    return _sync_storage_client(storage_api_token, storage_api_url)


@pytest.fixture
def keboola_client(sync_storage_client: SyncStorageClient) -> KeboolaClient:
    return KeboolaClient(
        storage_api_token=sync_storage_client.token,
        storage_api_url=sync_storage_client.root_url,
        headers={'User-Agent': INTEGTEST_USER_AGENT},
    )


@pytest.fixture
def unique_id() -> str:
    """Generates a unique ID string for test resources."""
    return str(uuid.uuid4())[:8]


@pytest_asyncio.fixture
async def workspace_manager(keboola_client: KeboolaClient, workspace_schema: str) -> WorkspaceManager:
    return await WorkspaceManager.create(keboola_client, workspace_schema)


@pytest_asyncio.fixture()
async def require_snowflake(workspace_manager: WorkspaceManager) -> None:
    sql_dialect = await workspace_manager.get_sql_dialect()
    if sql_dialect != 'Snowflake':
        pytest.skip(f'Snowflake backend required, got: {sql_dialect}')


@pytest_asyncio.fixture()
async def require_bigquery(workspace_manager: WorkspaceManager) -> None:
    sql_dialect = await workspace_manager.get_sql_dialect()
    if sql_dialect != 'BigQuery':
        pytest.skip(f'BigQuery backend required, got: {sql_dialect}')


@pytest.fixture
def mcp_context(
    mocker,
    keboola_client: KeboolaClient,
    workspace_manager: WorkspaceManager,
    keboola_project: ProjectDef,
    mcp_config: Config,
) -> Context:
    """
    MCP context containing the Keboola client and workspace manager.
    """
    client_context = mocker.MagicMock(Context)
    client_context.session = mocker.MagicMock(ServerSession)
    # We set the user session state as it is done in the @with_session_state decorator
    client_context.session.state = {
        KeboolaClient.STATE_KEY: keboola_client,
        WorkspaceManager.STATE_KEY: workspace_manager,
    }
    client_context.session.client_params = InitializeRequestParams(
        protocolVersion='1',
        capabilities=ClientCapabilities(),
        clientInfo=INTEGTEST_CLIENT_INFO,
    )
    client_context.client_id = INTEGTEST_USER_AGENT
    client_context.session_id = None
    client_context.request_context = mocker.MagicMock(RequestContext)
    client_context.request_context.lifespan_context = ServerState(mcp_config, ServerRuntimeInfo(transport='stdio'))
    # `meta` is an instance attribute of RequestContext (set in __init__), not a class attribute,
    # so MagicMock(spec=RequestContext) doesn't expose it. Default it to None so tools that read
    # the progressToken (e.g. query_data) don't trip AttributeError; individual tests can override.
    client_context.request_context.meta = None

    return client_context


@pytest.fixture
def mcp_server(storage_api_url: str, storage_api_token: str, workspace_schema: str) -> FastMCP:
    config = Config(storage_api_url=storage_api_url, storage_token=storage_api_token, workspace_schema=workspace_schema)
    server = create_server(config, runtime_info=ServerRuntimeInfo(transport='stdio'))
    assert isinstance(server, FastMCP)
    return server


@pytest_asyncio.fixture
async def mcp_client(mcp_server: FastMCP) -> AsyncGenerator[Client, None]:
    async with Client(mcp_server, client_info=INTEGTEST_CLIENT_INFO) as client:
        yield client
